### ISSUE TITLE
[Idea]: Using decorators for defining routes

### ISSUE THREAD

**Issue by knownasilya** [davewasmer/denali#4]
### Issue

Currently the way that routes are defined creates a big gap between the route definition and implementation. So your controllers have some methods and they might be named what the route is, but who knows really, until you look at `config/routes.js`. So there is a disconnect and someone reading the code has to find the definition of the routes elsewhere. It makes the code harder to understand and reason about. This makes refactoring harder as well.

### Possible Solution

Use decorators inside of the controller to assign route information to the implementations (see [express-decorators]) and use `config/routes.js` to change the order that controllers are added to the server/init decorated controllers.

```js
@controller('/users')
class Users {
  @get('/')
  listAll(req, res) {
    // return all users
  }
}
```

Then in the `config/routes.js` you could instantiate the decorated controller.

```js
UserController.setupRoutes(this);
```

This could be built in, or possibly as a separate module (might not need to be a plugin).

If this is built in and the way to define routes, the routes config might just be an array or controller names, e.g.

```js
export default [
  'users',
  'posts'
];
```

### Issues/Drawbacks

Decorators are not stable yet (but close).

[express-decorators]: https://github.com/stewartml/express-decorators

**Comment by davewasmer** [comment]
I've got mixed feelings about this approach. I sympathize with the idea that it's an additional step to mentally connect the controller to it's route, but I imagine for most APIs that are roughly "RESTful", it should be fairly obvious (i.e. the Books.create action is probably tied to `POST /books`).

You also lose the DRYness of something like `this.resource('books')`, which wires up multiple CRUD routes simultaneously.

Finally, most popular server frameworks have this kind of separation. While I don't want to just duplicate Rails et al blindly, I do think it's a good idea to be cautious when choosing a decidedly different approach.

I think this could make for a great userland module, and if it works well / has enough interest, we could add to core. 

For an implementation, assuming a hypothetical `denali-decorator-routes` module:

```js
// config/routes.js
import { setupRoutes } from 'denali-decorator-routes';

export default setupRoutes;
```

```js
// app/controllers/books.js
import { route } from 'denali-decorator-routes';
import { Controller } from 'denali';

export default Controller.extend({
  @post('/books')
  create() {
    // ...
  }
});
```
Does that make sense?

**Comment by davewasmer** [comment]
Closing this for now, but userland contributions are certainly welcome, as is further discussion on the topic.
